### ISSUE TITLE
Failed with `pip install -r requirements.txt`

### ISSUE THREAD

**Issue by fangzheng-mediagamma** [georgianpartners/automl_benchmark#1]
Thanks for your insightful benchmarking. I'm quite interested in reproducing the experiments you have done. However, the same error occurs for both MacOS 10.14 and Ubuntu Server 16.04 LTS. Any advice would be much appreciated:

Collecting xgboost==0.7.post3 (from auto_sklearn->-r requirements_3.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/cb/1c/a2ec1798d444e2b86b27fdbf18d9ab08c25c3d374de77429b55a76f42404/xgboost-0.7.post3.tar.gz
    Complete output from command python setup.py egg_info:
    + pwd
    + oldpath=/tmp/pip-install-9__hcxje/xgboost
    + cd ./xgboost/
    + [[  == darwin* ]]
    ./xgboost/build-python.sh: 19: ./xgboost/build-python.sh: [[: not found
    + LIB_XGBOOST=libxgboost.so
    + make lib/libxgboost.so -j4
    ./xgboost/build-python.sh: 25: ./xgboost/build-python.sh: make: not found
    + echo -----------------------------
    -----------------------------
    + echo Building multi-thread xgboost failed
    Building multi-thread xgboost failed
    + echo Start to build single-thread xgboost
    Start to build single-thread xgboost
    + make clean
    ./xgboost/build-python.sh: 31: ./xgboost/build-python.sh: make: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9__hcxje/xgboost/setup.py", line 37, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/tmp/pip-install-9__hcxje/xgboost/xgboost/libpath.py", line 49, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /tmp/pip-install-9__hcxje/xgboost/xgboost/libxgboost.so
    /tmp/pip-install-9__hcxje/xgboost/xgboost/../../lib/libxgboost.so
    /tmp/pip-install-9__hcxje/xgboost/xgboost/./lib/libxgboost.so
    /home/ubuntu/automl_benchmark/xgboost/libxgboost.so

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-9__hcxje/xgboost/

**Comment by robocoder99** [comment]
From looking at your error message it appears make is not installed on your system. You can install make on Ubuntu using apt or on macOS using brew. 

I don't believe make is installed by default on either of the systems you listed. I would recommend installing on Ubuntu and first doing

`sudo apt update`
`sudo apt install build-essential`

That will install most of the dependencies you need. If you continue to have issues you may attempt to install the xgboost dependency manually for which instructions can be found [here](https://xgboost.readthedocs.io/en/latest/build.html).

 Let me know if you have any further questions or issues. Thanks for your interest!

**Comment by adithyabsk** [comment]
Closing stale issue
